In [30]:
import pandas as pd
import numpy as np
import collections

fldnames = ['time', 'bound', 'st1', 'st2', 'n', 'v1', 'v2', 'v3']
df = pd.read_csv('subwayhopo.csv', names=fldnames, header=0, na_values=[])

In [33]:
df.head(100)

,time,bound,st1,st2,n,v1,v2,v3
0,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.187877,0.107574
1,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.193848,0.106580
2,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.193848,0.110554
3,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.188872,0.112540
4,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.189867,0.109560
5,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.195838,0.111547
6,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.191857,0.111547
7,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.195838,0.108567
8,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.192853,0.099627
9,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.194843,0.109560
10,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.196833,0.118488
11,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.203787,0.115520
12,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.200814,0.123454
13,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.205778,0.120475
14,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.199819,0.123454
15,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.197828,0.117507
16,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.202792,0.113533
17,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.195838,0.101614
18,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.202792,0.102607
19,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.199819,0.101614
20,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.185887,0.108567
21,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.192853,0.107574
22,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.191857,0.110554
23,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.186882,0.103601
24,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.194843,0.113533
25,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.193848,0.111547
26,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.196833,0.112540
27,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.196833,0.112540
28,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.185887,0.114527
29,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.194843,0.121468
...,...,...,...,...,...,...,...,...
70,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.174952,0.123454
71,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.169976,0.116513
72,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.168981,0.114527
73,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.172962,0.108567
74,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.166991,0.106580
75,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.164005,0.115520
76,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.165996,0.116513
77,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.159030,0.120475
78,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.165001,0.119481
79,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.165001,0.109560
80,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.160025,0.107574
81,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.167986,0.106580
82,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.159030,0.111547
83,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.158035,0.111547
84,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.160025,0.111547
85,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.153071,0.115520
86,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.152076,0.107574
87,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.153071,0.110554
88,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.147100,0.103601
89,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.150085,0.098634
90,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.152076,0.103601
91,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.149090,0.110554
92,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.150085,0.110554
93,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.149090,0.111547
94,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.145110,0.111547
95,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.155061,0.109560
96,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.144115,0.107574
97,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.147100,0.107574
98,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.150085,0.105587
99,2017-03-02AM 6:50:39,ANPYUNG_bound,youngsanDae,Dongbusan,3,9.34375,1.146105,0.105587

In [23]:
grouped = df.groupby(['st2','n'])
print(grouped.groups)

{('Dongbusan', 3): Int64Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
            ...
            123, 124, 125, 126, 127, 128, 129, 130, 131, 132],
           dtype='int64', length=133), ('Dongbusan', 1084): Int64Index([133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145,
            146, 147, 148, 149, 150, 151],
           dtype='int64')}

In [25]:
df2 = df.loc[grouped.groups[('Dongbusan', 3)]]

In [26]:
df3 = df.loc[grouped.groups[('Dongbusan', ???)]]

In [27]:
df2.describe()

           n         v1          v2          v3
count  133.0  133.00000  133.000000  133.000000
mean     3.0    9.34375    1.171793    0.112463
std      0.0    0.00000    0.026777    0.006597
min      3.0    9.34375    1.119248    0.097641
25%      3.0    9.34375    1.150085    0.107574
50%      3.0    9.34375    1.184892    0.111547
75%      3.0    9.34375    1.194843    0.116513
max      3.0    9.34375    1.210753    0.130407

In [28]:
df3.describe()

            n         v1         v2         v3
count    19.0  19.000000  19.000000  19.000000
mean   1084.0  17.609375   1.233264   0.113477
std       0.0   0.000000   0.005630   0.009132
min    1084.0  17.609375   1.222695   0.097641
25%    1084.0  17.609375   1.230147   0.108070
50%    1084.0  17.609375   1.231639   0.111547
75%    1084.0  17.609375   1.237113   0.120971
max    1084.0  17.609375   1.243581   0.127428

In [ ]:

# 3개 필드에 대한 합을 구하기 위해.
# np.zeros(4) --> 4개의 0.0으로 구성된 array 생성.
# 4개중에 제일앞 값은 개수 count 용.  뒤 3개는 v1, v2, v3 필드값 합계용
D = collections.defaultdict(lambda : np.zeros(4))

# 시간값(time필드)를 기준으로 동일
for r in df.itertuples():
  key = '%s,%s,%s,%s,%d' % (r.time, r.bound, r.st1, r.st2, r.n)
  D[key] += [1, r.v1, r.v2, r.v3]

# 시간값 목록 소팅
keys = list(D.keys())
keys.sort()

# 결과파일
out = open('out.csv', 'w')

for k in keys:
  v = D[k]
  # v[0] == 해당 key의 데이터 건수임. 그러므로 나누기를 해야함.
  v[1] = v[1] / v[0]
  v[2] = v[2] / v[0]
  v[3] = v[3] / v[0]
  line = '%s,%.4f,%.4f,%.4f' % (k, v[1], v[2], v[3])
  out.write(line + '\n') # 파일 저장
  print(line) # 화면으로도 출력하기 위해